# Site settings
author: Elektropay
baseurl: ""
brand: Sakura
copyright: abts.io
description: A secure and easy to use commerce as a service platform, process payments, send money and more...
email: hello@elektropay.com 
title: Elektropay 
url: "https://elektropay.com"

# Not using because Gulp is now processing SCSS
# sass:
#   sass_dir: css
#   style: compressed

# Algolia Search
algolia:
  application_id: 4P42FOBOZA # Use your (non-admin) search only api key here.
  index_name: sakura #Use an index you created on Algolia.

# Collections
collections:
  docs:
    output: true
    permalink: "/:collection/:path/"
  posts:
    output: true
    permalink: "/:collection/:title/"

# Defaults : these allow you to set default values for front matter
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post 
      type: post
  - scope:
      path: "pages"
      type: pages
    values:
      layout: default 
  - scope:
      path: "_docs"
      type: docs
    values:
      layout: post
      type: doc

# Exclude from Jekyll processing
exclude: [
  "_assets",
  "Gemfile",
  "Gemfile.lock",
  "gulpfile.js",
  "node_modules",
  "package.json",
  "publish.sh", 
  "yarn-error.log",
  "yarn.lock"
]

# Pagination (using jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 4 
  paginate_path: "/page:num"
  sort_reverse: true
  title: ":title"
  trail:
    before: 2
    after: 2

# Plugins
plugins: [jekyll-paginate-v2, jemoji, jekyll-sitemap, jekyll-seo-tag]

# SEO
social:
  name: Elektropay
  links:
    - https://github.com/elektropay
    - https://www.linkedin.com/in/elektropay/
webmaster_verifications:
  google: uubLfpcORmDWkM8pI-yKODVVZD3VSpUYFSwkQJcOuZE


# Social icons
show_social_icons: true
facebook_username: 
github_username: elektropay 
googleplus_username: 
linkedin_username: everpay
slack_username: 
twitter_username: 

# Syntax highlighting <= disables built-in highlighter so that we can use Prism
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
